#!/bin/bash
### BEGIN INIT INFO
# Provides:          loffice
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop LibreOffive Headless server
### END INIT INFO

LOFFICE=/usr/bin/loffice
PIDFILE=/var/run/libreoffice-server.pid
set -e
case "$1" in
    start)
        if [ -f $PIDFILE ]; then
            echo "LibreOffice headless server has already started."
            sleep 5
            exit
        fi
        echo "Starting LibreOffice headless server"
        $LOFFICE --headless --accept="socket,host=127.0.0.1,port=8100;urp;" --nofirststartwizard & > /dev/null 2>&1
        touch $PIDFILE
        ;;
    stop)
        if [ -f $PIDFILE ]; then
            echo "Stopping LibreOffice headless server."
            killall -9 loffice && killall -9 loffice.bin
            rm -f $PIDFILE
            exit
        fi
        echo "Libreoffice headless server is not running."
        exit
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0

